### ISSUE TITLE
Questions about sharing the model code used in the experiment.

### ISSUE THREAD

**Issue by m28yhtd** [sosppxo/MDIN#14]
Table 1 of your paper shows the results of the 3D-STMN experiment in Multi3DRes,
Could you share the save_graph.py file, scannetv2.py file, and test.py and train.py files of the 3D-STMN model that conducted the experiment?

**Comment by Liuuuuuyh** [comment]
Thank you for your attention. However, 3D-STMN is not a contribution to this work, so we have no plans to organize and release this part of the code in the short term. When we have time later, we will organize and release this part of the 3D-STMN code. Compared to the original 3D-STMN version, the key modifications are as follows: First, the mask supervision signal during training is formed by concatenating the ground truth (GT) masks of all the target instances. Second, since the 3D-STMN does not include a specific prediction mechanism for zero-target cases, any output with fewer than 50 mask points is classified as a zero-target scenario.

**Comment by m28yhtd** [comment]
Thank you for your response.
